import { Component, OnInit, Output } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-ficha',
  templateUrl: './ficha.component.html',
  styleUrls: ['./ficha.component.css']
})
export class FichaComponent implements OnInit {
  usuario: any;
  opcion : string;
  usuarios:any[] =[
    {id:"1", titulo:"Caperucita Roja", autor:"Charles Perrault", editorial :"Ediciones B / Zeta", descripcion :"La pequeña Caperucita es aquí una niña más traviesa de la que aparece en el original francés, que se entretiene recogiendo flores y habla con desconocidos, facilitando así las malas artes del lobo. Un conejito llamado Totó presencia la escena y, pese a avisarla una y otra vez de las intenciones del Lobo Feroz, no consigue que la niña le haga caso ni evitar que ésta esté a punto de ser devorada por la fiera. En vista de la situación, Totó corre a avisar a los lugareños que llegan milagro...", img:"https://images-na.ssl-images-amazon.com/images/I/611XC8oQN%2BL._SX442_BO1,204,203,200_.jpg"},
    {id:"1", titulo:"Los tres cerditos", autor:"Burt Gillett", editorial :"Ediciones B / Zeta", descripcion :"Los tres cochinitos es una fábula con personajes animales personificados. Las primeras ediciones datan del siglo XIX, pero se piensa que la historia es mucho más antigua. La historia ganó significado en el folclore universal gracias a la versión de dibujos animados de Walt Disney, en 1933.", img:"https://www.picarona.net/wp-content/uploads/2016/01/20150701102359.jpg"},
    {id:"1", titulo:"Alicia en El Pais de las Maravillas", autor:"Lewis Carroll", editorial :"Ediciones B / Zeta", descripcion :"Alicia es una niña imaginativa que solía inventarse situaciones de fantasía mientras hablaba sola. Una tarde de verano, se fue a descansar con su hermana a la orilla del río Támesis. Aburrida por el libro de su hermana mayor, Alicia pronto ve a un Conejo Blanco que parecía llegar tarde a algún sitio, y le sigue con curiosidad hasta su madriguera. ", img:"https://cloud10.todocoleccion.online/comics/tc/2012/03/25/31031627.jpg"},
    {id:"1", titulo:"El Patito Feo", autor:"Hans Christian Andersen", editorial :"Ediciones B / Zeta", descripcion :"Una pata tiene varios patitos, pero uno de ellos es mucho más feo, tosco y torpe que el resto, por lo que todos le dan de lado y se burlan de él. El patito decide huir de allí y se enfrenta solo y triste a los problemas del invierno. Al llegar la primavera, encuentra un grupo de cisnes que, para su sorpresa, son amables con él. Estos le hacen ver su reflejo en el estanque, y así descubrir que en realidad él era un bello cisne y no un pato desgarbado.", img:"https://imagessl4.casadellibro.com/a/l/t0/94/9788430524594.jpg"},
    {id:"1", titulo:"Pinocho", autor:"Carlo Collodi", editorial :"Ediciones B / Zeta", descripcion :"Pinocho es una marioneta, creado a partir de un tronco de pino, por el anciano Geppetto. Mientras Geppetto duerme, aparece el Hada Azul, quien beneficia a Geppetto por ser una buena persona dando vida al muñeco de madera. El Hada le dice que puede convertirse en un níño de verdad si es bueno.", img:"https://http2.mlstatic.com/dvd-pinocho-pinocchio-1940-ben-sharpsteen-disney-D_NQ_NP_803550-MLM26763827522_022018-F.webp"},
    {id:"1", titulo:"El Gato con Botas", autor:"Charles Perrault", editorial :"Claude Barbin", descripcion :"Es un gato anaranjado muy valiente, agil, desafiante, sabio que usaba botas junto a su chaleco y sombrero sin olvidar que a su lado siempre lleva una espada y se comportaba como un mosquetero. Tiene su mirada tierna para que lo distingan y lo vean como un lindo gatito muy inteligente.", img:"https://static3planetadelibroscom.cdnstatics.com/usuaris/libros/fotos/213/m_libros/portada_las-aventuras-del-gato-con-botas-en-guardia_dreamworks_201604190929.jpg"},
    {id:"1", titulo:"Hanzel y Gretel", autor:"Jacob Grimm", editorial :"Hermanos Grimm", descripcion :"Hansel y Gretel son hijos de un pobre leñador que no tiene con qué mantenerlos y, en un año de terrible hambruna, los abandona en el bosque para que mueran. Los niños encuentran en el bosque la casa de una bruja y se sorprenden al ver que está fabricada con dulces", img:"https://teatroaranjuez.es/wp-content/uploads/2018/10/hansel-y-gretel-cartel330x467.jpg"},
    {id:"1", titulo:"Jack y los Frijoles Magicos", autor:"Rupert Gregson-Williams", editorial :"Ediciones B / Zeta", descripcion :"Había una vez una viuda y su hijo Jack, que vivían en su pequeña granja en el campo. Cada día, Jack ayudaba a su madre con las tareas – cortaba leña, desherbaba la huerta y ordeñaba la vaca.  Pero a pesar de todo su arduo trabajo, Jack y su madre eran muy pobres y apenas tenían el dinero suficiente para alimentarse.", img:"http://www.delfineditorial.com.mx/catalogo/images/abook/cuento%20jack%20y%20los%20frijoles.png"},
    {id:"1", titulo:"Rapunzel", autor:"Hermanos Grimm", editorial :"Hermanos Grimm", descripcion :"Rapunzel es un cuento de hadas de la colección de los Hermanos Grimm.​ En la colección de cuentos de los Hermanos Grimm, Rapunzel es el n.º 12.​ Corresponde al tipo 310 de la clasificación de Aarne-Thompson: La doncella en la torre.", img:"https://imagessl2.casadellibro.com/m/ig/2/5942352.jpg"},
    {id:"1", titulo:"La Cenicienta", autor:"Hermanos Grimm", editorial :"Cuentos de Charles Perrault", descripcion :"Personajes Cenicienta: Se trata de una joven rubia de ojos azules muy hermosa. Vive con su madrastra y sus hermanastras y se dedica a realizar las tareas del hogar. ... ", img:"https://imagessl8.casadellibro.com/a/l/t0/28/9783815575628.jpg"},
    {id:"1", titulo:"La Bella y la Bestia", autor:"Gabrielle-Suzanne Barbot de Villeneuve", editorial :"DISNEY LIBROS", descripcion :"Belle, una joven hermosa y brillante, asume el lugar de su padre como prisionero en el castillo de una bestia. Poco a poco, la valiente Belle irá dándose cuenta de que el príncipe bestia no es el malvado ser que todos creen que es y tiene, en realidad, un gran corazón.", img:"https://imagessl4.casadellibro.com/a/l/t0/34/9788499518534.jpg"},
    {id:"1", titulo:"Ricitos de Oro y los tres Osos", autor:"Robert Southey", editorial :"Dylar's editorial", descripcion :"La historia cuenta el encuentro entre tres osos antropomórficos y una niña llamada Ricitos de Oro por su cabellera rubia. Una familia de osos compuesta por un papá, una mamá y de su hijo pequeño vive en una pequeña casa en un bosque. Un día, esperando a que su sopa se enfríe, la familia oso sale a dar un paseo.", img:"https://pictures.abebooks.com/isbn/9788467582352-es.jpg"}
    
  ];

  usuarios2:any[] =[
    {id:"1", titulo:"Caperucita Roja", autor:"Charles Perrault", editorial :"Ediciones B / Zeta", descripcion :"La pequeña Caperucita es aquí una niña más traviesa de la que aparece en el original francés, que se entretiene recogiendo flores y habla con desconocidos, facilitando así las malas artes del lobo. Un conejito llamado Totó presencia la escena y, pese a avisarla una y otra vez de las intenciones del Lobo Feroz, no consigue que la niña le haga caso ni evitar que ésta esté a punto de ser devorada por la fiera. En vista de la situación, Totó corre a avisar a los lugareños que llegan milagro...", img:"https://images-na.ssl-images-amazon.com/images/I/611XC8oQN%2BL._SX442_BO1,204,203,200_.jpg"},
    {id:"1", titulo:"Los tres cerditos", autor:"Burt Gillett", editorial :"Ediciones B / Zeta", descripcion :"Los tres cochinitos es una fábula con personajes animales personificados. Las primeras ediciones datan del siglo XIX, pero se piensa que la historia es mucho más antigua. La historia ganó significado en el folclore universal gracias a la versión de dibujos animados de Walt Disney, en 1933.", img:"https://www.picarona.net/wp-content/uploads/2016/01/20150701102359.jpg"},
    {id:"1", titulo:"Alicia en El Pais de las Maravillas", autor:"Lewis Carroll", editorial :"Ediciones B / Zeta", descripcion :"Alicia es una niña imaginativa que solía inventarse situaciones de fantasía mientras hablaba sola. Una tarde de verano, se fue a descansar con su hermana a la orilla del río Támesis. Aburrida por el libro de su hermana mayor, Alicia pronto ve a un Conejo Blanco que parecía llegar tarde a algún sitio, y le sigue con curiosidad hasta su madriguera. ", img:"https://cloud10.todocoleccion.online/comics/tc/2012/03/25/31031627.jpg"},
    {id:"1", titulo:"El Patito Feo", autor:"Hans Christian Andersen", editorial :"Ediciones B / Zeta", descripcion :"Una pata tiene varios patitos, pero uno de ellos es mucho más feo, tosco y torpe que el resto, por lo que todos le dan de lado y se burlan de él. El patito decide huir de allí y se enfrenta solo y triste a los problemas del invierno. Al llegar la primavera, encuentra un grupo de cisnes que, para su sorpresa, son amables con él. Estos le hacen ver su reflejo en el estanque, y así descubrir que en realidad él era un bello cisne y no un pato desgarbado.", img:"https://imagessl4.casadellibro.com/a/l/t0/94/9788430524594.jpg"},
    {id:"1", titulo:"Pinocho", autor:"Carlo Collodi", editorial :"Ediciones B / Zeta", descripcion :"Pinocho es una marioneta, creado a partir de un tronco de pino, por el anciano Geppetto. Mientras Geppetto duerme, aparece el Hada Azul, quien beneficia a Geppetto por ser una buena persona dando vida al muñeco de madera. El Hada le dice que puede convertirse en un níño de verdad si es bueno.", img:"https://http2.mlstatic.com/dvd-pinocho-pinocchio-1940-ben-sharpsteen-disney-D_NQ_NP_803550-MLM26763827522_022018-F.webp"},
    {id:"1", titulo:"El Gato con Botas", autor:"Charles Perrault", editorial :"Claude Barbin", descripcion :"Es un gato anaranjado muy valiente, agil, desafiante, sabio que usaba botas junto a su chaleco y sombrero sin olvidar que a su lado siempre lleva una espada y se comportaba como un mosquetero. Tiene su mirada tierna para que lo distingan y lo vean como un lindo gatito muy inteligente.", img:"https://static3planetadelibroscom.cdnstatics.com/usuaris/libros/fotos/213/m_libros/portada_las-aventuras-del-gato-con-botas-en-guardia_dreamworks_201604190929.jpg"},
    {id:"1", titulo:"Hanzel y Gretel", autor:"Jacob Grimm", editorial :"Hermanos Grimm", descripcion :"Hansel y Gretel son hijos de un pobre leñador que no tiene con qué mantenerlos y, en un año de terrible hambruna, los abandona en el bosque para que mueran. Los niños encuentran en el bosque la casa de una bruja y se sorprenden al ver que está fabricada con dulces", img:"https://teatroaranjuez.es/wp-content/uploads/2018/10/hansel-y-gretel-cartel330x467.jpg"},
    {id:"1", titulo:"Jack y los Frijoles Magicos", autor:"Rupert Gregson-Williams", editorial :"Ediciones B / Zeta", descripcion :"Había una vez una viuda y su hijo Jack, que vivían en su pequeña granja en el campo. Cada día, Jack ayudaba a su madre con las tareas – cortaba leña, desherbaba la huerta y ordeñaba la vaca.  Pero a pesar de todo su arduo trabajo, Jack y su madre eran muy pobres y apenas tenían el dinero suficiente para alimentarse.", img:"http://www.delfineditorial.com.mx/catalogo/images/abook/cuento%20jack%20y%20los%20frijoles.png"},
    {id:"1", titulo:"Rapunzel", autor:"Hermanos Grimm", editorial :"Hermanos Grimm", descripcion :"Rapunzel es un cuento de hadas de la colección de los Hermanos Grimm.​ En la colección de cuentos de los Hermanos Grimm, Rapunzel es el n.º 12.​ Corresponde al tipo 310 de la clasificación de Aarne-Thompson: La doncella en la torre.", img:"https://imagessl2.casadellibro.com/m/ig/2/5942352.jpg"},
    {id:"1", titulo:"La Cenicienta", autor:"Hermanos Grimm", editorial :"Cuentos de Charles Perrault", descripcion :"Personajes Cenicienta: Se trata de una joven rubia de ojos azules muy hermosa. Vive con su madrastra y sus hermanastras y se dedica a realizar las tareas del hogar. ... ", img:"https://imagessl8.casadellibro.com/a/l/t0/28/9783815575628.jpg"},
    {id:"1", titulo:"La Bella y la Bestia", autor:"Gabrielle-Suzanne Barbot de Villeneuve", editorial :"DISNEY LIBROS", descripcion :"Belle, una joven hermosa y brillante, asume el lugar de su padre como prisionero en el castillo de una bestia. Poco a poco, la valiente Belle irá dándose cuenta de que el príncipe bestia no es el malvado ser que todos creen que es y tiene, en realidad, un gran corazón.", img:"https://imagessl4.casadellibro.com/a/l/t0/34/9788499518534.jpg"},
    {id:"1", titulo:"Ricitos de Oro y los tres Osos", autor:"Robert Southey", editorial :"Dylar's editorial", descripcion :"La historia cuenta el encuentro entre tres osos antropomórficos y una niña llamada Ricitos de Oro por su cabellera rubia. Una familia de osos compuesta por un papá, una mamá y de su hijo pequeño vive en una pequeña casa en un bosque. Un día, esperando a que su sopa se enfríe, la familia oso sale a dar un paseo.", img:"https://pictures.abebooks.com/isbn/9788467582352-es.jpg"}
    
  ];

  usuarios3:any[] =[
    {id:"1", titulo:"Caperucita Roja", autor:"Charles Perrault", editorial :"Ediciones B / Zeta", descripcion :"La pequeña Caperucita es aquí una niña más traviesa de la que aparece en el original francés, que se entretiene recogiendo flores y habla con desconocidos, facilitando así las malas artes del lobo. Un conejito llamado Totó presencia la escena y, pese a avisarla una y otra vez de las intenciones del Lobo Feroz, no consigue que la niña le haga caso ni evitar que ésta esté a punto de ser devorada por la fiera. En vista de la situación, Totó corre a avisar a los lugareños que llegan milagro...", img:"https://images-na.ssl-images-amazon.com/images/I/611XC8oQN%2BL._SX442_BO1,204,203,200_.jpg"},
    {id:"1", titulo:"Los tres cerditos", autor:"Burt Gillett", editorial :"Ediciones B / Zeta", descripcion :"Los tres cochinitos es una fábula con personajes animales personificados. Las primeras ediciones datan del siglo XIX, pero se piensa que la historia es mucho más antigua. La historia ganó significado en el folclore universal gracias a la versión de dibujos animados de Walt Disney, en 1933.", img:"https://www.picarona.net/wp-content/uploads/2016/01/20150701102359.jpg"},
    {id:"1", titulo:"Alicia en El Pais de las Maravillas", autor:"Lewis Carroll", editorial :"Ediciones B / Zeta", descripcion :"Alicia es una niña imaginativa que solía inventarse situaciones de fantasía mientras hablaba sola. Una tarde de verano, se fue a descansar con su hermana a la orilla del río Támesis. Aburrida por el libro de su hermana mayor, Alicia pronto ve a un Conejo Blanco que parecía llegar tarde a algún sitio, y le sigue con curiosidad hasta su madriguera. ", img:"https://cloud10.todocoleccion.online/comics/tc/2012/03/25/31031627.jpg"},
    {id:"1", titulo:"El Patito Feo", autor:"Hans Christian Andersen", editorial :"Ediciones B / Zeta", descripcion :"Una pata tiene varios patitos, pero uno de ellos es mucho más feo, tosco y torpe que el resto, por lo que todos le dan de lado y se burlan de él. El patito decide huir de allí y se enfrenta solo y triste a los problemas del invierno. Al llegar la primavera, encuentra un grupo de cisnes que, para su sorpresa, son amables con él. Estos le hacen ver su reflejo en el estanque, y así descubrir que en realidad él era un bello cisne y no un pato desgarbado.", img:"https://imagessl4.casadellibro.com/a/l/t0/94/9788430524594.jpg"},
    {id:"1", titulo:"Pinocho", autor:"Carlo Collodi", editorial :"Ediciones B / Zeta", descripcion :"Pinocho es una marioneta, creado a partir de un tronco de pino, por el anciano Geppetto. Mientras Geppetto duerme, aparece el Hada Azul, quien beneficia a Geppetto por ser una buena persona dando vida al muñeco de madera. El Hada le dice que puede convertirse en un níño de verdad si es bueno.", img:"https://http2.mlstatic.com/dvd-pinocho-pinocchio-1940-ben-sharpsteen-disney-D_NQ_NP_803550-MLM26763827522_022018-F.webp"},
    {id:"1", titulo:"El Gato con Botas", autor:"Charles Perrault", editorial :"Claude Barbin", descripcion :"Es un gato anaranjado muy valiente, agil, desafiante, sabio que usaba botas junto a su chaleco y sombrero sin olvidar que a su lado siempre lleva una espada y se comportaba como un mosquetero. Tiene su mirada tierna para que lo distingan y lo vean como un lindo gatito muy inteligente.", img:"https://static3planetadelibroscom.cdnstatics.com/usuaris/libros/fotos/213/m_libros/portada_las-aventuras-del-gato-con-botas-en-guardia_dreamworks_201604190929.jpg"},
    {id:"1", titulo:"Hanzel y Gretel", autor:"Jacob Grimm", editorial :"Hermanos Grimm", descripcion :"Hansel y Gretel son hijos de un pobre leñador que no tiene con qué mantenerlos y, en un año de terrible hambruna, los abandona en el bosque para que mueran. Los niños encuentran en el bosque la casa de una bruja y se sorprenden al ver que está fabricada con dulces", img:"https://teatroaranjuez.es/wp-content/uploads/2018/10/hansel-y-gretel-cartel330x467.jpg"},
    {id:"1", titulo:"Jack y los Frijoles Magicos", autor:"Rupert Gregson-Williams", editorial :"Ediciones B / Zeta", descripcion :"Había una vez una viuda y su hijo Jack, que vivían en su pequeña granja en el campo. Cada día, Jack ayudaba a su madre con las tareas – cortaba leña, desherbaba la huerta y ordeñaba la vaca.  Pero a pesar de todo su arduo trabajo, Jack y su madre eran muy pobres y apenas tenían el dinero suficiente para alimentarse.", img:"http://www.delfineditorial.com.mx/catalogo/images/abook/cuento%20jack%20y%20los%20frijoles.png"},
    {id:"1", titulo:"Rapunzel", autor:"Hermanos Grimm", editorial :"Hermanos Grimm", descripcion :"Rapunzel es un cuento de hadas de la colección de los Hermanos Grimm.​ En la colección de cuentos de los Hermanos Grimm, Rapunzel es el n.º 12.​ Corresponde al tipo 310 de la clasificación de Aarne-Thompson: La doncella en la torre.", img:"https://imagessl2.casadellibro.com/m/ig/2/5942352.jpg"},
    {id:"1", titulo:"La Cenicienta", autor:"Hermanos Grimm", editorial :"Cuentos de Charles Perrault", descripcion :"Personajes Cenicienta: Se trata de una joven rubia de ojos azules muy hermosa. Vive con su madrastra y sus hermanastras y se dedica a realizar las tareas del hogar. ... ", img:"https://imagessl8.casadellibro.com/a/l/t0/28/9783815575628.jpg"},
    {id:"1", titulo:"La Bella y la Bestia", autor:"Gabrielle-Suzanne Barbot de Villeneuve", editorial :"DISNEY LIBROS", descripcion :"Belle, una joven hermosa y brillante, asume el lugar de su padre como prisionero en el castillo de una bestia. Poco a poco, la valiente Belle irá dándose cuenta de que el príncipe bestia no es el malvado ser que todos creen que es y tiene, en realidad, un gran corazón.", img:"https://imagessl4.casadellibro.com/a/l/t0/34/9788499518534.jpg"},
    {id:"1", titulo:"Ricitos de Oro y los tres Osos", autor:"Robert Southey", editorial :"Dylar's editorial", descripcion :"La historia cuenta el encuentro entre tres osos antropomórficos y una niña llamada Ricitos de Oro por su cabellera rubia. Una familia de osos compuesta por un papá, una mamá y de su hijo pequeño vive en una pequeña casa en un bosque. Un día, esperando a que su sopa se enfríe, la familia oso sale a dar un paseo.", img:"https://pictures.abebooks.com/isbn/9788467582352-es.jpg"}
    
  ];
  

    //Ordenando los libros segun su titulo
  usueditorial : any[] = this.usuarios2.sort(function(a,b){
    return a.editorial.localeCompare(b.editorial);
  });

  usutit : any[] = this.usuarios3.sort(function(a,b){
    return a.titulo.localeCompare(b.titulo);
  });



  

  constructor(private modalService: NgbModal){}

  
  



ver(usuario: any, modal){
    this.usuario = usuario
    this.modalService.open(modal); 
   
}

elegir(mensaje){
  this.opcion = mensaje;
}


  ngOnInit() {
    this.opcion = "";
  }

}
